# Generated by Django 4.2.5 on 2023-09-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2'), ('category3', 'Category 3')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArizaHomiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=250, verbose_name='I, F, SH')),
                ('phone', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(max_length=250)),
                ('Izoh', models.TextField()),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spon.category')),
            ],
        ),
    ]
