# Generated by Django 4.2.5 on 2023-09-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arizahomiy',
            old_name='Izoh',
            new_name='comment',
        ),
    ]
