# Generated by Django 4.2.5 on 2023-09-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spon', '0002_rename_izoh_arizahomiy_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arizahomiy',
            name='payment',
        ),
    ]
