# Generated by Django 4.2.5 on 2023-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spon', '0003_remove_arizahomiy_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('homiy', 'Homiy ')], max_length=20),
        ),
    ]
