# Generated by Django 4.2.4 on 2023-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spon', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizahomiy',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
